export default {
  products: [
    {
      _id: 1,
      name: "Man Shirt",
      category: "Shirt",
      image: "/images/man-shirt.jpg",
      price: "60",
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: 2,
      name: "Blue Shirt",
      category: "Shirt",
      image: "/images/man-shirt.jpg",
      price: "30",
      brand: "Adidas",
      rating: 3.5,
      numReviews: 8,
    },
    {
      _id: 3,
      name: "Slim Shirt",
      category: "Shirt",
      image: "/images/man-shirt.jpg",
      price: "20",
      brand: "Polo",
      rating: 2.5,
      numReviews: 5,
    },
    {
      _id: 4,
      name: "Short Shirt",
      category: "Shirt",
      image: "/images/man-shirt.jpg",
      price: "28",
      brand: "Reebok",
      rating: 3.8,
      numReviews: 7.5,
    },
  ],
};
